kind: Job
apiVersion: batch/v1
metadata:
  annotations:
    trivy-operator.container-images: '{"image-pruner":"quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:65d09a0cb625c88a174cba54a016fa32698af579163e222f1392fcf038991485"}'
  resourceVersion: '2917540'
  name: scan-vulnerabilityreport-57c6f5788b
  uid: 55113c37-2d55-474c-8a35-618715093eb0
  creationTimestamp: '2025-11-18T07:43:07Z'
  generation: 1
  managedFields:
    - manager: trivy-operator
      operation: Update
      apiVersion: batch/v1
      time: '2025-11-18T07:43:07Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:trivy-operator.container-images': {}
          'f:labels':
            .: {}
            'f:app.kubernetes.io/managed-by': {}
            'f:resource-spec-hash': {}
            'f:trivy-operator.resource.kind': {}
            'f:trivy-operator.resource.name': {}
            'f:trivy-operator.resource.namespace': {}
            'f:vulnerabilityReport.scanner': {}
        'f:spec':
          'f:completions': {}
          'f:backoffLimit': {}
          'f:ttlSecondsAfterFinished': {}
          'f:parallelism': {}
          'f:suspend': {}
          'f:activeDeadlineSeconds': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:app.kubernetes.io/managed-by': {}
                'f:resource-spec-hash': {}
                'f:trivy-operator.resource.kind': {}
                'f:trivy-operator.resource.name': {}
                'f:trivy-operator.resource.namespace': {}
                'f:vulnerabilityReport.scanner': {}
            'f:spec':
              'f:volumes':
                .: {}
                'k:{"name":"scanresult"}':
                  .: {}
                  'f:emptyDir': {}
                  'f:name': {}
                'k:{"name":"tmp"}':
                  .: {}
                  'f:emptyDir': {}
                  'f:name': {}
              'f:containers':
                'k:{"name":"image-pruner"}':
                  'f:image': {}
                  'f:volumeMounts':
                    .: {}
                    'k:{"mountPath":"/tmp"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                    'k:{"mountPath":"/tmp/scan"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                  'f:terminationMessagePolicy': {}
                  .: {}
                  'f:resources':
                    .: {}
                    'f:limits':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                    'f:requests':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                  'f:args': {}
                  'f:command': {}
                  'f:env':
                    'k:{"name":"TRIVY_TIMEOUT"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:configMapKeyRef': {}
                    'k:{"name":"TRIVY_IGNORE_UNFIXED"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:configMapKeyRef': {}
                    'k:{"name":"TRIVY_JAVA_DB_REPOSITORY"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:configMapKeyRef': {}
                    'k:{"name":"TRIVY_SKIP_DIRS"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:configMapKeyRef': {}
                    'k:{"name":"TRIVY_SKIP_FILES"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:configMapKeyRef': {}
                    'k:{"name":"HTTPS_PROXY"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:configMapKeyRef': {}
                    .: {}
                    'k:{"name":"TRIVY_OFFLINE_SCAN"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:configMapKeyRef': {}
                    'k:{"name":"TRIVY_SEVERITY"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:configMapKeyRef': {}
                    'k:{"name":"NO_PROXY"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:configMapKeyRef': {}
                    'k:{"name":"HTTP_PROXY"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:configMapKeyRef': {}
                  'f:securityContext':
                    .: {}
                    'f:allowPrivilegeEscalation': {}
                    'f:capabilities':
                      .: {}
                      'f:drop': {}
                    'f:privileged': {}
                    'f:readOnlyRootFilesystem': {}
                  'f:terminationMessagePath': {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
              'f:dnsPolicy': {}
              'f:automountServiceAccountToken': {}
              'f:serviceAccount': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:terminationGracePeriodSeconds': {}
              'f:initContainers':
                .: {}
                'k:{"name":"3f1987c8-7236-40fa-a27f-8d86d0ba5e17"}':
                  'f:image': {}
                  'f:volumeMounts':
                    .: {}
                    'k:{"mountPath":"/tmp"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                  'f:terminationMessagePolicy': {}
                  .: {}
                  'f:resources':
                    .: {}
                    'f:limits':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                    'f:requests':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                  'f:args': {}
                  'f:command': {}
                  'f:env':
                    .: {}
                    'k:{"name":"GITHUB_TOKEN"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:secretKeyRef': {}
                    'k:{"name":"HTTPS_PROXY"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:configMapKeyRef': {}
                    'k:{"name":"HTTP_PROXY"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:configMapKeyRef': {}
                    'k:{"name":"NO_PROXY"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:configMapKeyRef': {}
                  'f:securityContext':
                    .: {}
                    'f:allowPrivilegeEscalation': {}
                    'f:capabilities':
                      .: {}
                      'f:drop': {}
                    'f:privileged': {}
                    'f:readOnlyRootFilesystem': {}
                  'f:terminationMessagePath': {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
              'f:serviceAccountName': {}
              'f:securityContext': {}
              'f:affinity':
                .: {}
                'f:nodeAffinity':
                  .: {}
                  'f:requiredDuringSchedulingIgnoredDuringExecution': {}
          'f:podReplacementPolicy': {}
          'f:completionMode': {}
          'f:manualSelector': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: batch/v1
      time: '2025-11-18T07:44:27Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:conditions': {}
          'f:failed': {}
          'f:ready': {}
          'f:startTime': {}
          'f:terminating': {}
          'f:uncountedTerminatedPods': {}
      subresource: status
  namespace: aqua
  labels:
    app.kubernetes.io/managed-by: trivy-operator
    resource-spec-hash: 6555d6f9dc
    trivy-operator.resource.kind: CronJob
    trivy-operator.resource.name: image-pruner
    trivy-operator.resource.namespace: openshift-image-registry
    vulnerabilityReport.scanner: Trivy
spec:
  activeDeadlineSeconds: 300
  manualSelector: false
  backoffLimit: 0
  completions: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        vulnerabilityReport.scanner: Trivy
        trivy-operator.resource.name: image-pruner
        resource-spec-hash: 6555d6f9dc
        trivy-operator.resource.namespace: openshift-image-registry
        trivy-operator.resource.kind: CronJob
        batch.kubernetes.io/job-name: scan-vulnerabilityreport-57c6f5788b
        app.kubernetes.io/managed-by: trivy-operator
        batch.kubernetes.io/controller-uid: 55113c37-2d55-474c-8a35-618715093eb0
        job-name: scan-vulnerabilityreport-57c6f5788b
        controller-uid: 55113c37-2d55-474c-8a35-618715093eb0
    spec:
      restartPolicy: Never
      initContainers:
        - resources:
            limits:
              cpu: 500m
              memory: 500M
            requests:
              cpu: 100m
              memory: 100M
          terminationMessagePath: /dev/termination-log
          name: 3f1987c8-7236-40fa-a27f-8d86d0ba5e17
          command:
            - trivy
          env:
            - name: HTTP_PROXY
              valueFrom:
                configMapKeyRef:
                  name: trivy-operator-trivy-config
                  key: trivy.httpProxy
                  optional: true
            - name: HTTPS_PROXY
              valueFrom:
                configMapKeyRef:
                  name: trivy-operator-trivy-config
                  key: trivy.httpsProxy
                  optional: true
            - name: NO_PROXY
              valueFrom:
                configMapKeyRef:
                  name: trivy-operator-trivy-config
                  key: trivy.noProxy
                  optional: true
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: trivy-operator-trivy-config
                  key: trivy.githubToken
                  optional: true
          securityContext:
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          terminationMessagePolicy: FallbackToLogsOnError
          image: 'mirror.gcr.io/aquasec/trivy:0.67.0'
          args:
            - '--cache-dir'
            - /tmp/trivy/.cache
            - image
            - '--download-db-only'
            - '--db-repository'
            - mirror.gcr.io/aquasec/trivy-db
      serviceAccountName: trivy-operator
      schedulerName: default-scheduler
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources:
            limits:
              cpu: 500m
              memory: 500M
            requests:
              cpu: 100m
              memory: 100M
          terminationMessagePath: /dev/termination-log
          name: image-pruner
          command:
            - /bin/sh
          env:
            - name: TRIVY_SEVERITY
              valueFrom:
                configMapKeyRef:
                  name: trivy-operator-trivy-config
                  key: trivy.severity
                  optional: true
            - name: TRIVY_IGNORE_UNFIXED
              valueFrom:
                configMapKeyRef:
                  name: trivy-operator-trivy-config
                  key: trivy.ignoreUnfixed
                  optional: true
            - name: TRIVY_OFFLINE_SCAN
              valueFrom:
                configMapKeyRef:
                  name: trivy-operator-trivy-config
                  key: trivy.offlineScan
                  optional: true
            - name: TRIVY_JAVA_DB_REPOSITORY
              valueFrom:
                configMapKeyRef:
                  name: trivy-operator-trivy-config
                  key: trivy.javaDbRepository
                  optional: true
            - name: TRIVY_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: trivy-operator-trivy-config
                  key: trivy.timeout
                  optional: true
            - name: TRIVY_SKIP_FILES
              valueFrom:
                configMapKeyRef:
                  name: trivy-operator-trivy-config
                  key: trivy.skipFiles
                  optional: true
            - name: TRIVY_SKIP_DIRS
              valueFrom:
                configMapKeyRef:
                  name: trivy-operator-trivy-config
                  key: trivy.skipDirs
                  optional: true
            - name: HTTP_PROXY
              valueFrom:
                configMapKeyRef:
                  name: trivy-operator-trivy-config
                  key: trivy.httpProxy
                  optional: true
            - name: HTTPS_PROXY
              valueFrom:
                configMapKeyRef:
                  name: trivy-operator-trivy-config
                  key: trivy.httpsProxy
                  optional: true
            - name: NO_PROXY
              valueFrom:
                configMapKeyRef:
                  name: trivy-operator-trivy-config
                  key: trivy.noProxy
                  optional: true
          securityContext:
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: scanresult
              mountPath: /tmp/scan
          terminationMessagePolicy: FallbackToLogsOnError
          image: 'mirror.gcr.io/aquasec/trivy:0.67.0'
          args:
            - '-c'
            - 'trivy image quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:65d09a0cb625c88a174cba54a016fa32698af579163e222f1392fcf038991485 --cache-dir /tmp/trivy/.cache --format json --image-config-scanners secret --scanners secret --skip-db-update --slow --list-all-pkgs --output /tmp/scan/result_image-pruner.json 2>/tmp/scan/result_image-pruner.json.log && bzip2 -c /tmp/scan/result_image-pruner.json | base64'
      automountServiceAccountToken: false
      serviceAccount: trivy-operator
      volumes:
        - name: tmp
          emptyDir: {}
        - name: scanresult
          emptyDir: {}
      dnsPolicy: ClusterFirst
  ttlSecondsAfterFinished: 86400
  suspend: false
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  completionMode: NonIndexed
  selector:
    matchLabels:
      batch.kubernetes.io/controller-uid: 55113c37-2d55-474c-8a35-618715093eb0
status:
  conditions:
    - type: Failed
      status: 'True'
      lastProbeTime: '2025-11-18T07:44:27Z'
      lastTransitionTime: '2025-11-18T07:44:27Z'
      reason: BackoffLimitExceeded
      message: Job has reached the specified backoff limit
  startTime: '2025-11-18T07:43:07Z'
  failed: 1
  terminating: 0
  uncountedTerminatedPods: {}
  ready: 0
