---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aquasecurity.aquasec.com
  resources:
  - aquastarboards
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aquasecurity.aquasec.com
  resources:
  - aquastarboards/finalizers
  verbs:
  - update
- apiGroups:
  - aquasecurity.aquasec.com
  resources:
  - aquastarboards/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquacsps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquacsps/finalizers
  verbs:
  - update
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquacsps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquadatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquadatabases/finalizers
  verbs:
  - update
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquadatabases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquaenforcers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquaenforcers/finalizers
  verbs:
  - update
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquaenforcers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquagateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquagateways/finalizers
  verbs:
  - update
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquagateways/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquakubeenforcers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquakubeenforcers/finalizers
  verbs:
  - update
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquakubeenforcers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquascanners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquascanners/finalizers
  verbs:
  - update
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquascanners/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquaservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquaservers/finalizers
  verbs:
  - update
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquaservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - route
  resources:
  - routes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
