// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaCommon) DeepCopyInto(out *AquaCommon) {
	*out = *in
	if in.AdminPassword != nil {
		in, out := &in.AdminPassword, &out.AdminPassword
		*out = new(AquaSecret)
		**out = **in
	}
	if in.AquaLicense != nil {
		in, out := &in.AquaLicense, &out.AquaLicense
		*out = new(AquaSecret)
		**out = **in
	}
	if in.DatabaseSecret != nil {
		in, out := &in.DatabaseSecret, &out.DatabaseSecret
		*out = new(AquaSecret)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaCommon.
func (in *AquaCommon) DeepCopy() *AquaCommon {
	if in == nil {
		return nil
	}
	out := new(AquaCommon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaCsp) DeepCopyInto(out *AquaCsp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaCsp.
func (in *AquaCsp) DeepCopy() *AquaCsp {
	if in == nil {
		return nil
	}
	out := new(AquaCsp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AquaCsp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaCspList) DeepCopyInto(out *AquaCspList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AquaCsp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaCspList.
func (in *AquaCspList) DeepCopy() *AquaCspList {
	if in == nil {
		return nil
	}
	out := new(AquaCspList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AquaCspList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaCspSpec) DeepCopyInto(out *AquaCspSpec) {
	*out = *in
	if in.Infrastructure != nil {
		in, out := &in.Infrastructure, &out.Infrastructure
		*out = new(AquaInfrastructure)
		**out = **in
	}
	if in.Common != nil {
		in, out := &in.Common, &out.Common
		*out = new(AquaCommon)
		(*in).DeepCopyInto(*out)
	}
	if in.RegistryData != nil {
		in, out := &in.RegistryData, &out.RegistryData
		*out = new(AquaDockerRegistry)
		**out = **in
	}
	if in.ExternalDb != nil {
		in, out := &in.ExternalDb, &out.ExternalDb
		*out = new(AquaDatabaseInformation)
		**out = **in
	}
	if in.DbService != nil {
		in, out := &in.DbService, &out.DbService
		*out = new(AquaService)
		(*in).DeepCopyInto(*out)
	}
	if in.GatewayService != nil {
		in, out := &in.GatewayService, &out.GatewayService
		*out = new(AquaService)
		(*in).DeepCopyInto(*out)
	}
	if in.ServerService != nil {
		in, out := &in.ServerService, &out.ServerService
		*out = new(AquaService)
		(*in).DeepCopyInto(*out)
	}
	if in.Enforcer != nil {
		in, out := &in.Enforcer, &out.Enforcer
		*out = new(AquaEnforcerDetailes)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaCspSpec.
func (in *AquaCspSpec) DeepCopy() *AquaCspSpec {
	if in == nil {
		return nil
	}
	out := new(AquaCspSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaCspStatus) DeepCopyInto(out *AquaCspStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaCspStatus.
func (in *AquaCspStatus) DeepCopy() *AquaCspStatus {
	if in == nil {
		return nil
	}
	out := new(AquaCspStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaDatabase) DeepCopyInto(out *AquaDatabase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaDatabase.
func (in *AquaDatabase) DeepCopy() *AquaDatabase {
	if in == nil {
		return nil
	}
	out := new(AquaDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AquaDatabase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaDatabaseInformation) DeepCopyInto(out *AquaDatabaseInformation) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaDatabaseInformation.
func (in *AquaDatabaseInformation) DeepCopy() *AquaDatabaseInformation {
	if in == nil {
		return nil
	}
	out := new(AquaDatabaseInformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaDatabaseList) DeepCopyInto(out *AquaDatabaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AquaDatabase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaDatabaseList.
func (in *AquaDatabaseList) DeepCopy() *AquaDatabaseList {
	if in == nil {
		return nil
	}
	out := new(AquaDatabaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AquaDatabaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaDatabaseSpec) DeepCopyInto(out *AquaDatabaseSpec) {
	*out = *in
	if in.Infrastructure != nil {
		in, out := &in.Infrastructure, &out.Infrastructure
		*out = new(AquaInfrastructure)
		**out = **in
	}
	if in.Common != nil {
		in, out := &in.Common, &out.Common
		*out = new(AquaCommon)
		(*in).DeepCopyInto(*out)
	}
	if in.DbService != nil {
		in, out := &in.DbService, &out.DbService
		*out = new(AquaService)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaDatabaseSpec.
func (in *AquaDatabaseSpec) DeepCopy() *AquaDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(AquaDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaDatabaseStatus) DeepCopyInto(out *AquaDatabaseStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaDatabaseStatus.
func (in *AquaDatabaseStatus) DeepCopy() *AquaDatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(AquaDatabaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaDockerRegistry) DeepCopyInto(out *AquaDockerRegistry) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaDockerRegistry.
func (in *AquaDockerRegistry) DeepCopy() *AquaDockerRegistry {
	if in == nil {
		return nil
	}
	out := new(AquaDockerRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaEnforcer) DeepCopyInto(out *AquaEnforcer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaEnforcer.
func (in *AquaEnforcer) DeepCopy() *AquaEnforcer {
	if in == nil {
		return nil
	}
	out := new(AquaEnforcer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AquaEnforcer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaEnforcerDetailes) DeepCopyInto(out *AquaEnforcerDetailes) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaEnforcerDetailes.
func (in *AquaEnforcerDetailes) DeepCopy() *AquaEnforcerDetailes {
	if in == nil {
		return nil
	}
	out := new(AquaEnforcerDetailes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaEnforcerList) DeepCopyInto(out *AquaEnforcerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AquaEnforcer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaEnforcerList.
func (in *AquaEnforcerList) DeepCopy() *AquaEnforcerList {
	if in == nil {
		return nil
	}
	out := new(AquaEnforcerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AquaEnforcerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaEnforcerSpec) DeepCopyInto(out *AquaEnforcerSpec) {
	*out = *in
	if in.Infrastructure != nil {
		in, out := &in.Infrastructure, &out.Infrastructure
		*out = new(AquaInfrastructure)
		**out = **in
	}
	if in.Common != nil {
		in, out := &in.Common, &out.Common
		*out = new(AquaCommon)
		(*in).DeepCopyInto(*out)
	}
	if in.EnforcerService != nil {
		in, out := &in.EnforcerService, &out.EnforcerService
		*out = new(AquaService)
		(*in).DeepCopyInto(*out)
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(AquaGatewayInformation)
		**out = **in
	}
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(AquaSecret)
		**out = **in
	}
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaEnforcerSpec.
func (in *AquaEnforcerSpec) DeepCopy() *AquaEnforcerSpec {
	if in == nil {
		return nil
	}
	out := new(AquaEnforcerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaEnforcerStatus) DeepCopyInto(out *AquaEnforcerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaEnforcerStatus.
func (in *AquaEnforcerStatus) DeepCopy() *AquaEnforcerStatus {
	if in == nil {
		return nil
	}
	out := new(AquaEnforcerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaGateway) DeepCopyInto(out *AquaGateway) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaGateway.
func (in *AquaGateway) DeepCopy() *AquaGateway {
	if in == nil {
		return nil
	}
	out := new(AquaGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AquaGateway) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaGatewayInformation) DeepCopyInto(out *AquaGatewayInformation) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaGatewayInformation.
func (in *AquaGatewayInformation) DeepCopy() *AquaGatewayInformation {
	if in == nil {
		return nil
	}
	out := new(AquaGatewayInformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaGatewayList) DeepCopyInto(out *AquaGatewayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AquaGateway, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaGatewayList.
func (in *AquaGatewayList) DeepCopy() *AquaGatewayList {
	if in == nil {
		return nil
	}
	out := new(AquaGatewayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AquaGatewayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaGatewaySpec) DeepCopyInto(out *AquaGatewaySpec) {
	*out = *in
	if in.Infrastructure != nil {
		in, out := &in.Infrastructure, &out.Infrastructure
		*out = new(AquaInfrastructure)
		**out = **in
	}
	if in.Common != nil {
		in, out := &in.Common, &out.Common
		*out = new(AquaCommon)
		(*in).DeepCopyInto(*out)
	}
	if in.GatewayService != nil {
		in, out := &in.GatewayService, &out.GatewayService
		*out = new(AquaService)
		(*in).DeepCopyInto(*out)
	}
	if in.ExternalDb != nil {
		in, out := &in.ExternalDb, &out.ExternalDb
		*out = new(AquaDatabaseInformation)
		**out = **in
	}
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaGatewaySpec.
func (in *AquaGatewaySpec) DeepCopy() *AquaGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(AquaGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaGatewayStatus) DeepCopyInto(out *AquaGatewayStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaGatewayStatus.
func (in *AquaGatewayStatus) DeepCopy() *AquaGatewayStatus {
	if in == nil {
		return nil
	}
	out := new(AquaGatewayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaImage) DeepCopyInto(out *AquaImage) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaImage.
func (in *AquaImage) DeepCopy() *AquaImage {
	if in == nil {
		return nil
	}
	out := new(AquaImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaInfrastructure) DeepCopyInto(out *AquaInfrastructure) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaInfrastructure.
func (in *AquaInfrastructure) DeepCopy() *AquaInfrastructure {
	if in == nil {
		return nil
	}
	out := new(AquaInfrastructure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaLogin) DeepCopyInto(out *AquaLogin) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaLogin.
func (in *AquaLogin) DeepCopy() *AquaLogin {
	if in == nil {
		return nil
	}
	out := new(AquaLogin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaScanner) DeepCopyInto(out *AquaScanner) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaScanner.
func (in *AquaScanner) DeepCopy() *AquaScanner {
	if in == nil {
		return nil
	}
	out := new(AquaScanner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AquaScanner) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaScannerCliScale) DeepCopyInto(out *AquaScannerCliScale) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaScannerCliScale.
func (in *AquaScannerCliScale) DeepCopy() *AquaScannerCliScale {
	if in == nil {
		return nil
	}
	out := new(AquaScannerCliScale)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaScannerList) DeepCopyInto(out *AquaScannerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AquaScanner, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaScannerList.
func (in *AquaScannerList) DeepCopy() *AquaScannerList {
	if in == nil {
		return nil
	}
	out := new(AquaScannerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AquaScannerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaScannerSpec) DeepCopyInto(out *AquaScannerSpec) {
	*out = *in
	if in.Infrastructure != nil {
		in, out := &in.Infrastructure, &out.Infrastructure
		*out = new(AquaInfrastructure)
		**out = **in
	}
	if in.Common != nil {
		in, out := &in.Common, &out.Common
		*out = new(AquaCommon)
		(*in).DeepCopyInto(*out)
	}
	if in.ScannerService != nil {
		in, out := &in.ScannerService, &out.ScannerService
		*out = new(AquaService)
		(*in).DeepCopyInto(*out)
	}
	if in.Login != nil {
		in, out := &in.Login, &out.Login
		*out = new(AquaLogin)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaScannerSpec.
func (in *AquaScannerSpec) DeepCopy() *AquaScannerSpec {
	if in == nil {
		return nil
	}
	out := new(AquaScannerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaScannerStatus) DeepCopyInto(out *AquaScannerStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaScannerStatus.
func (in *AquaScannerStatus) DeepCopy() *AquaScannerStatus {
	if in == nil {
		return nil
	}
	out := new(AquaScannerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaSecret) DeepCopyInto(out *AquaSecret) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaSecret.
func (in *AquaSecret) DeepCopy() *AquaSecret {
	if in == nil {
		return nil
	}
	out := new(AquaSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaServer) DeepCopyInto(out *AquaServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaServer.
func (in *AquaServer) DeepCopy() *AquaServer {
	if in == nil {
		return nil
	}
	out := new(AquaServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AquaServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaServerList) DeepCopyInto(out *AquaServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AquaServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaServerList.
func (in *AquaServerList) DeepCopy() *AquaServerList {
	if in == nil {
		return nil
	}
	out := new(AquaServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AquaServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaServerSpec) DeepCopyInto(out *AquaServerSpec) {
	*out = *in
	if in.Infrastructure != nil {
		in, out := &in.Infrastructure, &out.Infrastructure
		*out = new(AquaInfrastructure)
		**out = **in
	}
	if in.Common != nil {
		in, out := &in.Common, &out.Common
		*out = new(AquaCommon)
		(*in).DeepCopyInto(*out)
	}
	if in.ServerService != nil {
		in, out := &in.ServerService, &out.ServerService
		*out = new(AquaService)
		(*in).DeepCopyInto(*out)
	}
	if in.ExternalDb != nil {
		in, out := &in.ExternalDb, &out.ExternalDb
		*out = new(AquaDatabaseInformation)
		**out = **in
	}
	if in.Enforcer != nil {
		in, out := &in.Enforcer, &out.Enforcer
		*out = new(AquaEnforcerDetailes)
		**out = **in
	}
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaServerSpec.
func (in *AquaServerSpec) DeepCopy() *AquaServerSpec {
	if in == nil {
		return nil
	}
	out := new(AquaServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaServerStatus) DeepCopyInto(out *AquaServerStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaServerStatus.
func (in *AquaServerStatus) DeepCopy() *AquaServerStatus {
	if in == nil {
		return nil
	}
	out := new(AquaServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaService) DeepCopyInto(out *AquaService) {
	*out = *in
	if in.ImageData != nil {
		in, out := &in.ImageData, &out.ImageData
		*out = new(AquaImage)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.LivenessProbe != nil {
		in, out := &in.LivenessProbe, &out.LivenessProbe
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadinessProbe != nil {
		in, out := &in.ReadinessProbe, &out.ReadinessProbe
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaService.
func (in *AquaService) DeepCopy() *AquaService {
	if in == nil {
		return nil
	}
	out := new(AquaService)
	in.DeepCopyInto(out)
	return out
}
