apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: aquakubeenforcers.operator.aquasec.com
spec:
  group: operator.aquasec.com
  names:
    kind: AquaKubeEnforcer
    listKind: AquaKubeEnforcerList
    plural: aquakubeenforcers
    singular: aquakubeenforcer
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          x-kubernetes-preserve-unknown-fields: true
          type: object
      served: true
      storage: true
      subresources:
        status: {}
