apiVersion: operator.aquasec.com/v1
kind: AquaKubeEnforcer
metadata:
  name: aqua
spec:
  infra:
    version: '6.5'
    serviceAccount: "aqua-kube-enforcer-sa"
  config:
    gateway_address: "aqua-gateway.aqua:8443"
    cluster_name: "aqua-secure"
    imagePullSecret: "aqua-registry"
  token: "<<KubeEnforcer Group Token>>"
  allowAnyVersion:                        # Optional: running all types of images
  deploy:
    service: ClusterIP
    image:
      registry: "registry.aquasec.com"
      tag: "6.5"
      repository: "kube-enforcer"
      pullPolicy: "Always"
    resources:                              # Optional: Set resources requests/limits for kube-enforcer
      limits:
        cpu: "SOME VALUE"
        memory: "SOME VALUE"
      requests:
        cpu: "SOME VALUE"
        memory: "SOME VALUE"
  env:                                      # Optional: environment variables to add to the kube-enforcer
  - name: "SOME ENV"
    value: "SOME ENV VALUE"


