//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaCloudConnector) DeepCopyInto(out *AquaCloudConnector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaCloudConnector.
func (in *AquaCloudConnector) DeepCopy() *AquaCloudConnector {
	if in == nil {
		return nil
	}
	out := new(AquaCloudConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AquaCloudConnector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaCloudConnectorList) DeepCopyInto(out *AquaCloudConnectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AquaCloudConnector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaCloudConnectorList.
func (in *AquaCloudConnectorList) DeepCopy() *AquaCloudConnectorList {
	if in == nil {
		return nil
	}
	out := new(AquaCloudConnectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AquaCloudConnectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaCloudConnectorSpec) DeepCopyInto(out *AquaCloudConnectorSpec) {
	*out = *in
	if in.Infrastructure != nil {
		in, out := &in.Infrastructure, &out.Infrastructure
		*out = new(AquaInfrastructure)
		**out = **in
	}
	if in.Common != nil {
		in, out := &in.Common, &out.Common
		*out = new(AquaCommon)
		(*in).DeepCopyInto(*out)
	}
	if in.CloudConnectorService != nil {
		in, out := &in.CloudConnectorService, &out.CloudConnectorService
		*out = new(AquaService)
		(*in).DeepCopyInto(*out)
	}
	if in.Login != nil {
		in, out := &in.Login, &out.Login
		*out = new(AquaLogin)
		**out = **in
	}
	if in.Tunnels != nil {
		in, out := &in.Tunnels, &out.Tunnels
		*out = make([]*AquaCloudConnectorTunnels, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(AquaCloudConnectorTunnels)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaCloudConnectorSpec.
func (in *AquaCloudConnectorSpec) DeepCopy() *AquaCloudConnectorSpec {
	if in == nil {
		return nil
	}
	out := new(AquaCloudConnectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaCloudConnectorStatus) DeepCopyInto(out *AquaCloudConnectorStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaCloudConnectorStatus.
func (in *AquaCloudConnectorStatus) DeepCopy() *AquaCloudConnectorStatus {
	if in == nil {
		return nil
	}
	out := new(AquaCloudConnectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaCloudConnectorTunnels) DeepCopyInto(out *AquaCloudConnectorTunnels) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaCloudConnectorTunnels.
func (in *AquaCloudConnectorTunnels) DeepCopy() *AquaCloudConnectorTunnels {
	if in == nil {
		return nil
	}
	out := new(AquaCloudConnectorTunnels)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaCommon) DeepCopyInto(out *AquaCommon) {
	*out = *in
	if in.AdminPassword != nil {
		in, out := &in.AdminPassword, &out.AdminPassword
		*out = new(AquaSecret)
		**out = **in
	}
	if in.AquaLicense != nil {
		in, out := &in.AquaLicense, &out.AquaLicense
		*out = new(AquaSecret)
		**out = **in
	}
	if in.DatabaseSecret != nil {
		in, out := &in.DatabaseSecret, &out.DatabaseSecret
		*out = new(AquaSecret)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaCommon.
func (in *AquaCommon) DeepCopy() *AquaCommon {
	if in == nil {
		return nil
	}
	out := new(AquaCommon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaCsp) DeepCopyInto(out *AquaCsp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaCsp.
func (in *AquaCsp) DeepCopy() *AquaCsp {
	if in == nil {
		return nil
	}
	out := new(AquaCsp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AquaCsp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaCspList) DeepCopyInto(out *AquaCspList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AquaCsp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaCspList.
func (in *AquaCspList) DeepCopy() *AquaCspList {
	if in == nil {
		return nil
	}
	out := new(AquaCspList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AquaCspList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaCspSpec) DeepCopyInto(out *AquaCspSpec) {
	*out = *in
	if in.Infrastructure != nil {
		in, out := &in.Infrastructure, &out.Infrastructure
		*out = new(AquaInfrastructure)
		**out = **in
	}
	if in.Common != nil {
		in, out := &in.Common, &out.Common
		*out = new(AquaCommon)
		(*in).DeepCopyInto(*out)
	}
	if in.RegistryData != nil {
		in, out := &in.RegistryData, &out.RegistryData
		*out = new(AquaDockerRegistry)
		**out = **in
	}
	if in.ExternalDb != nil {
		in, out := &in.ExternalDb, &out.ExternalDb
		*out = new(AquaDatabaseInformation)
		**out = **in
	}
	if in.AuditDB != nil {
		in, out := &in.AuditDB, &out.AuditDB
		*out = new(AuditDBInformation)
		(*in).DeepCopyInto(*out)
	}
	if in.DbService != nil {
		in, out := &in.DbService, &out.DbService
		*out = new(AquaService)
		(*in).DeepCopyInto(*out)
	}
	if in.GatewayService != nil {
		in, out := &in.GatewayService, &out.GatewayService
		*out = new(AquaService)
		(*in).DeepCopyInto(*out)
	}
	if in.ServerService != nil {
		in, out := &in.ServerService, &out.ServerService
		*out = new(AquaService)
		(*in).DeepCopyInto(*out)
	}
	if in.Enforcer != nil {
		in, out := &in.Enforcer, &out.Enforcer
		*out = new(AquaEnforcerDetailes)
		**out = **in
	}
	if in.ServerEnvs != nil {
		in, out := &in.ServerEnvs, &out.ServerEnvs
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GatewayEnvs != nil {
		in, out := &in.GatewayEnvs, &out.GatewayEnvs
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ServerConfigMapData != nil {
		in, out := &in.ServerConfigMapData, &out.ServerConfigMapData
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DeployKubeEnforcer != nil {
		in, out := &in.DeployKubeEnforcer, &out.DeployKubeEnforcer
		*out = new(AquaKubeEnforcerDetails)
		**out = **in
	}
	if in.EnforcerUpdateApproved != nil {
		in, out := &in.EnforcerUpdateApproved, &out.EnforcerUpdateApproved
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaCspSpec.
func (in *AquaCspSpec) DeepCopy() *AquaCspSpec {
	if in == nil {
		return nil
	}
	out := new(AquaCspSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaCspStatus) DeepCopyInto(out *AquaCspStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaCspStatus.
func (in *AquaCspStatus) DeepCopy() *AquaCspStatus {
	if in == nil {
		return nil
	}
	out := new(AquaCspStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaDatabase) DeepCopyInto(out *AquaDatabase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaDatabase.
func (in *AquaDatabase) DeepCopy() *AquaDatabase {
	if in == nil {
		return nil
	}
	out := new(AquaDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AquaDatabase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaDatabaseInformation) DeepCopyInto(out *AquaDatabaseInformation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaDatabaseInformation.
func (in *AquaDatabaseInformation) DeepCopy() *AquaDatabaseInformation {
	if in == nil {
		return nil
	}
	out := new(AquaDatabaseInformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaDatabaseList) DeepCopyInto(out *AquaDatabaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AquaDatabase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaDatabaseList.
func (in *AquaDatabaseList) DeepCopy() *AquaDatabaseList {
	if in == nil {
		return nil
	}
	out := new(AquaDatabaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AquaDatabaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaDatabaseSpec) DeepCopyInto(out *AquaDatabaseSpec) {
	*out = *in
	if in.Infrastructure != nil {
		in, out := &in.Infrastructure, &out.Infrastructure
		*out = new(AquaInfrastructure)
		**out = **in
	}
	if in.Common != nil {
		in, out := &in.Common, &out.Common
		*out = new(AquaCommon)
		(*in).DeepCopyInto(*out)
	}
	if in.DbService != nil {
		in, out := &in.DbService, &out.DbService
		*out = new(AquaService)
		(*in).DeepCopyInto(*out)
	}
	if in.AuditDB != nil {
		in, out := &in.AuditDB, &out.AuditDB
		*out = new(AuditDBInformation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaDatabaseSpec.
func (in *AquaDatabaseSpec) DeepCopy() *AquaDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(AquaDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaDatabaseStatus) DeepCopyInto(out *AquaDatabaseStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaDatabaseStatus.
func (in *AquaDatabaseStatus) DeepCopy() *AquaDatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(AquaDatabaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaDockerRegistry) DeepCopyInto(out *AquaDockerRegistry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaDockerRegistry.
func (in *AquaDockerRegistry) DeepCopy() *AquaDockerRegistry {
	if in == nil {
		return nil
	}
	out := new(AquaDockerRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaEnforcer) DeepCopyInto(out *AquaEnforcer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaEnforcer.
func (in *AquaEnforcer) DeepCopy() *AquaEnforcer {
	if in == nil {
		return nil
	}
	out := new(AquaEnforcer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AquaEnforcer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaEnforcerDetailes) DeepCopyInto(out *AquaEnforcerDetailes) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaEnforcerDetailes.
func (in *AquaEnforcerDetailes) DeepCopy() *AquaEnforcerDetailes {
	if in == nil {
		return nil
	}
	out := new(AquaEnforcerDetailes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaEnforcerList) DeepCopyInto(out *AquaEnforcerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AquaEnforcer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaEnforcerList.
func (in *AquaEnforcerList) DeepCopy() *AquaEnforcerList {
	if in == nil {
		return nil
	}
	out := new(AquaEnforcerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AquaEnforcerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaEnforcerSpec) DeepCopyInto(out *AquaEnforcerSpec) {
	*out = *in
	if in.Infrastructure != nil {
		in, out := &in.Infrastructure, &out.Infrastructure
		*out = new(AquaInfrastructure)
		**out = **in
	}
	if in.Common != nil {
		in, out := &in.Common, &out.Common
		*out = new(AquaCommon)
		(*in).DeepCopyInto(*out)
	}
	if in.EnforcerService != nil {
		in, out := &in.EnforcerService, &out.EnforcerService
		*out = new(AquaService)
		(*in).DeepCopyInto(*out)
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(AquaGatewayInformation)
		**out = **in
	}
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(AquaSecret)
		**out = **in
	}
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnforcerUpdateApproved != nil {
		in, out := &in.EnforcerUpdateApproved, &out.EnforcerUpdateApproved
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaEnforcerSpec.
func (in *AquaEnforcerSpec) DeepCopy() *AquaEnforcerSpec {
	if in == nil {
		return nil
	}
	out := new(AquaEnforcerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaEnforcerStatus) DeepCopyInto(out *AquaEnforcerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaEnforcerStatus.
func (in *AquaEnforcerStatus) DeepCopy() *AquaEnforcerStatus {
	if in == nil {
		return nil
	}
	out := new(AquaEnforcerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaGateway) DeepCopyInto(out *AquaGateway) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaGateway.
func (in *AquaGateway) DeepCopy() *AquaGateway {
	if in == nil {
		return nil
	}
	out := new(AquaGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AquaGateway) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaGatewayInformation) DeepCopyInto(out *AquaGatewayInformation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaGatewayInformation.
func (in *AquaGatewayInformation) DeepCopy() *AquaGatewayInformation {
	if in == nil {
		return nil
	}
	out := new(AquaGatewayInformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaGatewayList) DeepCopyInto(out *AquaGatewayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AquaGateway, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaGatewayList.
func (in *AquaGatewayList) DeepCopy() *AquaGatewayList {
	if in == nil {
		return nil
	}
	out := new(AquaGatewayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AquaGatewayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaGatewaySpec) DeepCopyInto(out *AquaGatewaySpec) {
	*out = *in
	if in.Infrastructure != nil {
		in, out := &in.Infrastructure, &out.Infrastructure
		*out = new(AquaInfrastructure)
		**out = **in
	}
	if in.Common != nil {
		in, out := &in.Common, &out.Common
		*out = new(AquaCommon)
		(*in).DeepCopyInto(*out)
	}
	if in.GatewayService != nil {
		in, out := &in.GatewayService, &out.GatewayService
		*out = new(AquaService)
		(*in).DeepCopyInto(*out)
	}
	if in.ExternalDb != nil {
		in, out := &in.ExternalDb, &out.ExternalDb
		*out = new(AquaDatabaseInformation)
		**out = **in
	}
	if in.AuditDB != nil {
		in, out := &in.AuditDB, &out.AuditDB
		*out = new(AuditDBInformation)
		(*in).DeepCopyInto(*out)
	}
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaGatewaySpec.
func (in *AquaGatewaySpec) DeepCopy() *AquaGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(AquaGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaGatewayStatus) DeepCopyInto(out *AquaGatewayStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaGatewayStatus.
func (in *AquaGatewayStatus) DeepCopy() *AquaGatewayStatus {
	if in == nil {
		return nil
	}
	out := new(AquaGatewayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaImage) DeepCopyInto(out *AquaImage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaImage.
func (in *AquaImage) DeepCopy() *AquaImage {
	if in == nil {
		return nil
	}
	out := new(AquaImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaInfrastructure) DeepCopyInto(out *AquaInfrastructure) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaInfrastructure.
func (in *AquaInfrastructure) DeepCopy() *AquaInfrastructure {
	if in == nil {
		return nil
	}
	out := new(AquaInfrastructure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaKubeEnforcer) DeepCopyInto(out *AquaKubeEnforcer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaKubeEnforcer.
func (in *AquaKubeEnforcer) DeepCopy() *AquaKubeEnforcer {
	if in == nil {
		return nil
	}
	out := new(AquaKubeEnforcer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AquaKubeEnforcer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaKubeEnforcerConfig) DeepCopyInto(out *AquaKubeEnforcerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaKubeEnforcerConfig.
func (in *AquaKubeEnforcerConfig) DeepCopy() *AquaKubeEnforcerConfig {
	if in == nil {
		return nil
	}
	out := new(AquaKubeEnforcerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaKubeEnforcerDetails) DeepCopyInto(out *AquaKubeEnforcerDetails) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaKubeEnforcerDetails.
func (in *AquaKubeEnforcerDetails) DeepCopy() *AquaKubeEnforcerDetails {
	if in == nil {
		return nil
	}
	out := new(AquaKubeEnforcerDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaKubeEnforcerList) DeepCopyInto(out *AquaKubeEnforcerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AquaKubeEnforcer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaKubeEnforcerList.
func (in *AquaKubeEnforcerList) DeepCopy() *AquaKubeEnforcerList {
	if in == nil {
		return nil
	}
	out := new(AquaKubeEnforcerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AquaKubeEnforcerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaKubeEnforcerSpec) DeepCopyInto(out *AquaKubeEnforcerSpec) {
	*out = *in
	if in.Infrastructure != nil {
		in, out := &in.Infrastructure, &out.Infrastructure
		*out = new(AquaInfrastructure)
		**out = **in
	}
	out.Config = in.Config
	if in.RegistryData != nil {
		in, out := &in.RegistryData, &out.RegistryData
		*out = new(AquaDockerRegistry)
		**out = **in
	}
	if in.ImageData != nil {
		in, out := &in.ImageData, &out.ImageData
		*out = new(AquaImage)
		**out = **in
	}
	if in.EnforcerUpdateApproved != nil {
		in, out := &in.EnforcerUpdateApproved, &out.EnforcerUpdateApproved
		*out = new(bool)
		**out = **in
	}
	if in.KubeEnforcerService != nil {
		in, out := &in.KubeEnforcerService, &out.KubeEnforcerService
		*out = new(AquaService)
		(*in).DeepCopyInto(*out)
	}
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DeployStarboard != nil {
		in, out := &in.DeployStarboard, &out.DeployStarboard
		*out = new(AquaStarboardDetails)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaKubeEnforcerSpec.
func (in *AquaKubeEnforcerSpec) DeepCopy() *AquaKubeEnforcerSpec {
	if in == nil {
		return nil
	}
	out := new(AquaKubeEnforcerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaKubeEnforcerStatus) DeepCopyInto(out *AquaKubeEnforcerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaKubeEnforcerStatus.
func (in *AquaKubeEnforcerStatus) DeepCopy() *AquaKubeEnforcerStatus {
	if in == nil {
		return nil
	}
	out := new(AquaKubeEnforcerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaLightning) DeepCopyInto(out *AquaLightning) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaLightning.
func (in *AquaLightning) DeepCopy() *AquaLightning {
	if in == nil {
		return nil
	}
	out := new(AquaLightning)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AquaLightning) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaLightningEnforcer) DeepCopyInto(out *AquaLightningEnforcer) {
	*out = *in
	if in.Infrastructure != nil {
		in, out := &in.Infrastructure, &out.Infrastructure
		*out = new(AquaInfrastructure)
		**out = **in
	}
	if in.EnforcerService != nil {
		in, out := &in.EnforcerService, &out.EnforcerService
		*out = new(AquaService)
		(*in).DeepCopyInto(*out)
	}
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(AquaSecret)
		**out = **in
	}
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnforcerUpdateApproved != nil {
		in, out := &in.EnforcerUpdateApproved, &out.EnforcerUpdateApproved
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaLightningEnforcer.
func (in *AquaLightningEnforcer) DeepCopy() *AquaLightningEnforcer {
	if in == nil {
		return nil
	}
	out := new(AquaLightningEnforcer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaLightningGlobal) DeepCopyInto(out *AquaLightningGlobal) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaLightningGlobal.
func (in *AquaLightningGlobal) DeepCopy() *AquaLightningGlobal {
	if in == nil {
		return nil
	}
	out := new(AquaLightningGlobal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaLightningKubeEnforcer) DeepCopyInto(out *AquaLightningKubeEnforcer) {
	*out = *in
	if in.Infrastructure != nil {
		in, out := &in.Infrastructure, &out.Infrastructure
		*out = new(AquaInfrastructure)
		**out = **in
	}
	if in.RegistryData != nil {
		in, out := &in.RegistryData, &out.RegistryData
		*out = new(AquaDockerRegistry)
		**out = **in
	}
	if in.ImageData != nil {
		in, out := &in.ImageData, &out.ImageData
		*out = new(AquaImage)
		**out = **in
	}
	if in.EnforcerUpdateApproved != nil {
		in, out := &in.EnforcerUpdateApproved, &out.EnforcerUpdateApproved
		*out = new(bool)
		**out = **in
	}
	if in.KubeEnforcerService != nil {
		in, out := &in.KubeEnforcerService, &out.KubeEnforcerService
		*out = new(AquaService)
		(*in).DeepCopyInto(*out)
	}
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DeployStarboard != nil {
		in, out := &in.DeployStarboard, &out.DeployStarboard
		*out = new(AquaStarboardDetails)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaLightningKubeEnforcer.
func (in *AquaLightningKubeEnforcer) DeepCopy() *AquaLightningKubeEnforcer {
	if in == nil {
		return nil
	}
	out := new(AquaLightningKubeEnforcer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaLightningList) DeepCopyInto(out *AquaLightningList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AquaLightning, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaLightningList.
func (in *AquaLightningList) DeepCopy() *AquaLightningList {
	if in == nil {
		return nil
	}
	out := new(AquaLightningList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AquaLightningList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaLightningSpec) DeepCopyInto(out *AquaLightningSpec) {
	*out = *in
	if in.Common != nil {
		in, out := &in.Common, &out.Common
		*out = new(AquaCommon)
		(*in).DeepCopyInto(*out)
	}
	if in.Global != nil {
		in, out := &in.Global, &out.Global
		*out = new(AquaLightningGlobal)
		**out = **in
	}
	if in.KubeEnforcer != nil {
		in, out := &in.KubeEnforcer, &out.KubeEnforcer
		*out = new(AquaLightningKubeEnforcer)
		(*in).DeepCopyInto(*out)
	}
	if in.Enforcer != nil {
		in, out := &in.Enforcer, &out.Enforcer
		*out = new(AquaLightningEnforcer)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaLightningSpec.
func (in *AquaLightningSpec) DeepCopy() *AquaLightningSpec {
	if in == nil {
		return nil
	}
	out := new(AquaLightningSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaLightningStatus) DeepCopyInto(out *AquaLightningStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaLightningStatus.
func (in *AquaLightningStatus) DeepCopy() *AquaLightningStatus {
	if in == nil {
		return nil
	}
	out := new(AquaLightningStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaLogin) DeepCopyInto(out *AquaLogin) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaLogin.
func (in *AquaLogin) DeepCopy() *AquaLogin {
	if in == nil {
		return nil
	}
	out := new(AquaLogin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaScanner) DeepCopyInto(out *AquaScanner) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaScanner.
func (in *AquaScanner) DeepCopy() *AquaScanner {
	if in == nil {
		return nil
	}
	out := new(AquaScanner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AquaScanner) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaScannerCliScale) DeepCopyInto(out *AquaScannerCliScale) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaScannerCliScale.
func (in *AquaScannerCliScale) DeepCopy() *AquaScannerCliScale {
	if in == nil {
		return nil
	}
	out := new(AquaScannerCliScale)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaScannerList) DeepCopyInto(out *AquaScannerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AquaScanner, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaScannerList.
func (in *AquaScannerList) DeepCopy() *AquaScannerList {
	if in == nil {
		return nil
	}
	out := new(AquaScannerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AquaScannerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaScannerSpec) DeepCopyInto(out *AquaScannerSpec) {
	*out = *in
	if in.Infrastructure != nil {
		in, out := &in.Infrastructure, &out.Infrastructure
		*out = new(AquaInfrastructure)
		**out = **in
	}
	if in.Common != nil {
		in, out := &in.Common, &out.Common
		*out = new(AquaCommon)
		(*in).DeepCopyInto(*out)
	}
	if in.ScannerService != nil {
		in, out := &in.ScannerService, &out.ScannerService
		*out = new(AquaService)
		(*in).DeepCopyInto(*out)
	}
	if in.Login != nil {
		in, out := &in.Login, &out.Login
		*out = new(AquaLogin)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaScannerSpec.
func (in *AquaScannerSpec) DeepCopy() *AquaScannerSpec {
	if in == nil {
		return nil
	}
	out := new(AquaScannerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaScannerStatus) DeepCopyInto(out *AquaScannerStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaScannerStatus.
func (in *AquaScannerStatus) DeepCopy() *AquaScannerStatus {
	if in == nil {
		return nil
	}
	out := new(AquaScannerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaSecret) DeepCopyInto(out *AquaSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaSecret.
func (in *AquaSecret) DeepCopy() *AquaSecret {
	if in == nil {
		return nil
	}
	out := new(AquaSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaServer) DeepCopyInto(out *AquaServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaServer.
func (in *AquaServer) DeepCopy() *AquaServer {
	if in == nil {
		return nil
	}
	out := new(AquaServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AquaServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaServerList) DeepCopyInto(out *AquaServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AquaServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaServerList.
func (in *AquaServerList) DeepCopy() *AquaServerList {
	if in == nil {
		return nil
	}
	out := new(AquaServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AquaServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaServerSpec) DeepCopyInto(out *AquaServerSpec) {
	*out = *in
	if in.Infrastructure != nil {
		in, out := &in.Infrastructure, &out.Infrastructure
		*out = new(AquaInfrastructure)
		**out = **in
	}
	if in.Common != nil {
		in, out := &in.Common, &out.Common
		*out = new(AquaCommon)
		(*in).DeepCopyInto(*out)
	}
	if in.ServerService != nil {
		in, out := &in.ServerService, &out.ServerService
		*out = new(AquaService)
		(*in).DeepCopyInto(*out)
	}
	if in.ExternalDb != nil {
		in, out := &in.ExternalDb, &out.ExternalDb
		*out = new(AquaDatabaseInformation)
		**out = **in
	}
	if in.AuditDB != nil {
		in, out := &in.AuditDB, &out.AuditDB
		*out = new(AuditDBInformation)
		(*in).DeepCopyInto(*out)
	}
	if in.Enforcer != nil {
		in, out := &in.Enforcer, &out.Enforcer
		*out = new(AquaEnforcerDetailes)
		**out = **in
	}
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ConfigMapData != nil {
		in, out := &in.ConfigMapData, &out.ConfigMapData
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaServerSpec.
func (in *AquaServerSpec) DeepCopy() *AquaServerSpec {
	if in == nil {
		return nil
	}
	out := new(AquaServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaServerStatus) DeepCopyInto(out *AquaServerStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaServerStatus.
func (in *AquaServerStatus) DeepCopy() *AquaServerStatus {
	if in == nil {
		return nil
	}
	out := new(AquaServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaService) DeepCopyInto(out *AquaService) {
	*out = *in
	if in.ImageData != nil {
		in, out := &in.ImageData, &out.ImageData
		*out = new(AquaImage)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.LivenessProbe != nil {
		in, out := &in.LivenessProbe, &out.LivenessProbe
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadinessProbe != nil {
		in, out := &in.ReadinessProbe, &out.ReadinessProbe
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]v1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]v1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaService.
func (in *AquaService) DeepCopy() *AquaService {
	if in == nil {
		return nil
	}
	out := new(AquaService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaStarboardConfig) DeepCopyInto(out *AquaStarboardConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaStarboardConfig.
func (in *AquaStarboardConfig) DeepCopy() *AquaStarboardConfig {
	if in == nil {
		return nil
	}
	out := new(AquaStarboardConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AquaStarboardDetails) DeepCopyInto(out *AquaStarboardDetails) {
	*out = *in
	if in.Infrastructure != nil {
		in, out := &in.Infrastructure, &out.Infrastructure
		*out = new(AquaInfrastructure)
		**out = **in
	}
	if in.StarboardService != nil {
		in, out := &in.StarboardService, &out.StarboardService
		*out = new(AquaService)
		(*in).DeepCopyInto(*out)
	}
	out.Config = in.Config
	if in.RegistryData != nil {
		in, out := &in.RegistryData, &out.RegistryData
		*out = new(AquaDockerRegistry)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.ImageData != nil {
		in, out := &in.ImageData, &out.ImageData
		*out = new(AquaImage)
		**out = **in
	}
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AquaStarboardDetails.
func (in *AquaStarboardDetails) DeepCopy() *AquaStarboardDetails {
	if in == nil {
		return nil
	}
	out := new(AquaStarboardDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditDBInformation) DeepCopyInto(out *AuditDBInformation) {
	*out = *in
	if in.AuditDBSecret != nil {
		in, out := &in.AuditDBSecret, &out.AuditDBSecret
		*out = new(AquaSecret)
		**out = **in
	}
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = new(AquaDatabaseInformation)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditDBInformation.
func (in *AuditDBInformation) DeepCopy() *AuditDBInformation {
	if in == nil {
		return nil
	}
	out := new(AuditDBInformation)
	in.DeepCopyInto(out)
	return out
}
